USE bank;
SET SQL_SAFE_UPDATES = 0;

CREATE USER IF NOT EXISTS jdbctest IDENTIFIED BY 'jdbctest';
GRANT INSERT, SELECT, UPDATE ON bank.Rekeningen TO jdbctest;

CREATE TABLE Rekeningen  IF NOT EXISTS(
	RekeningNr BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Saldo DECIMAL(12,2) NOT NULL DEFAULT 0.00
);


DELETE FROM Rekeningen;


